apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# CIS Kubernetes Benchmark v1.8.0
resources:
# Common CIS Kubernetes policies
- ../common
# Shared policy libraries (pod-security/restricted includes pod-security/baseline)
- ../../../pod-security/restricted
- ../../../rbac-best-practices
- ../../../best-practices-k8s
