apiVersion: v1
kind: Namespace
metadata:
  name: ns-without-pss
  labels:
    team: backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-with-wrong-label
  labels:
    pod-security.kubernetes.io/warn: restricted
