apiVersion: policies.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: validate-any-principal
  annotations:
    policies.kyverno.io/title: Validate Any Principal
    policies.kyverno.io/category: AWS S3 Security Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
     Principal value in an IAM policy specifies which user or entity
     is allowed or denied access to a resource. For policies attached
     to an S3 bucket, this policy validates if the Principal allowed is
     '*', which means ANY Principal is allowed access to the resource.
spec:
  validationActions:
    - Deny
  evaluation:
    mode: JSON
    background:
      enabled: false
  matchConstraints:
    resourceRules:
      - apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["*"]
        operations: ["CREATE", "UPDATE"]
  matchConditions:
    - name: is-terraform-plan
      expression: "has(object.resource_changes) && has(object.terraform_version)"
    - name: has-s3-bucket-policy
      expression: |
        object.resource_changes.exists(rc,
          rc.mode == 'managed'
          && rc.type == 'aws_s3_bucket_policy'
          && rc.change.actions.exists(a, a == 'create' || a == 'update'))
  variables:
    - name: resource_changes
      expression: |
        object.resource_changes.filter(rc,
          rc.mode == 'managed'
          && rc.change.actions.exists(a, a == 'create' || a == 'update'))
    - name: bucket_policies
      expression: "variables.resource_changes.filter(rc, rc.type == 'aws_s3_bucket_policy')"
  validations:
    - expression: |
        variables.bucket_policies.all(bp,
          !(bp.change.after.policy.orValue('').contains('"Principal":"*"') ||
            bp.change.after.policy.orValue('').contains('"Principal": "*"') ||
            bp.change.after.policy.orValue('').contains('"AWS":"*"') ||
            bp.change.after.policy.orValue('').contains('"AWS": "*"')))
      message: "Principal should not be set to '*' in the Bucket Policy."
