apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-without-tls
  namespace: default
spec:
  rules:
  - host: myapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: myapp
            port:
              number: 80
